### ISSUE TITLE
Marketing/Sponsoring List

### ISSUE THREAD

**Issue by itsmingjie** [srnd/clear#20]
Something big and may take a lot of time. Not sure if it's necessary, but may be useful.

It would be nice if we can use clear as a portal to track marketing/sponsor interactions.

So ideally, you would be able to create an entry for a certain company and log when you emailed or when they replied, current status, information about how they are interested, amount of sponsorship, failed/succeeded.

This database should be shared with your region so you don't overlap each other's contacts.

**Comment by tjhorner** [comment]
Thanks for the idea! This is good, but since it is very simple and internal, most organizers use a spreadsheet for this type of thing. For example, at CodeDay San Diego, we have a list of sponsors with, among other fields, a "status" field and an "assigned to" field. The status field includes the current status of the sponsor (contacted, awaiting response, rejected, accepted, etc.) and the other one includes who is assigned to what sponsor, reducing confusion.

So while this seems like a good idea, it does not require Clear for it to work efficiently. What you can do instead is create a spreadsheet for your event (a good idea in the first place), and place it in your internal notes so others can view it.

I'm going to keep this issue open in case we want to add this in the future.

**Comment by tylermenezes** [comment]
We have Salesforce set up for tracking national sponsorships this way. I could add you to Salesforce if you'd like, but it's probably more complicated than you'd like for local sponsorships. Another good option for tracking them would be Streak CRM.
